import "./globals.css";

import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "WhatsApp Clone",
    description: "Generated by developer Silvanei Martins",
};

type Props = {
    children: ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
